/** Historical and fictional opponent teams used in simulation + story copy */

export const CLASSIC_OPPONENTS = [
  { name: "1996 Chicago Bulls", strength: 98, era: "dynasty" },
  { name: "2017 Golden State Warriors", strength: 96, era: "dynasty" },
  { name: "1986 Boston Celtics", strength: 94, era: "dynasty" },
  { name: "2001 Los Angeles Lakers", strength: 93, era: "champion" },
  { name: "2013 Miami Heat", strength: 92, era: "champion" },
  { name: "2008 Boston Celtics", strength: 90, era: "champion" },
  { name: "2019 Toronto Raptors", strength: 88, era: "champion" },
  { name: "2020 Los Angeles Lakers", strength: 87, era: "champion" },
  { name: "2011 Dallas Mavericks", strength: 85, era: "champion" },
  { name: "2004 Detroit Pistons", strength: 84, era: "champion" },
  { name: "2018 Houston Rockets", strength: 86, era: "contender" },
  { name: "2023 Denver Nuggets", strength: 88, era: "champion" },
  { name: "2024 Boston Celtics", strength: 89, era: "champion" },
  { name: "1994 New York Knicks", strength: 82, era: "contender" },
  { name: "2006 Phoenix Suns", strength: 83, era: "contender" },
  { name: "2015 Atlanta Hawks", strength: 78, era: "contender" },
  { name: "2002 Sacramento Kings", strength: 84, era: "contender" },
  { name: "1999 San Antonio Spurs", strength: 87, era: "champion" },
  { name: "2016 Cleveland Cavaliers", strength: 86, era: "champion" },
  { name: "1993 Phoenix Suns", strength: 85, era: "contender" },
  { name: "2009 Orlando Magic", strength: 81, era: "contender" },
  { name: "2010 Los Angeles Lakers", strength: 88, era: "champion" },
  { name: "2021 Milwaukee Bucks", strength: 87, era: "champion" },
  { name: "1989 Detroit Pistons", strength: 86, era: "champion" },
  { name: "1997 Utah Jazz", strength: 84, era: "contender" },
  { name: "2014 Indiana Pacers", strength: 80, era: "contender" },
  { name: "2005 San Antonio Spurs", strength: 85, era: "champion" },
  { name: "2022 Golden State Warriors", strength: 86, era: "champion" },
  { name: "1992 Portland Trail Blazers", strength: 82, era: "contender" },
  { name: "2012 Oklahoma City Thunder", strength: 83, era: "contender" },
  { name: "2026 Sacramento Kings", strength: 52, era: "rebuild" },
  { name: "2026 Washington Wizards", strength: 48, era: "rebuild" },
  { name: "2026 Charlotte Hornets", strength: 47, era: "rebuild" },
  { name: "2026 Detroit Pistons", strength: 50, era: "rebuild" },
  { name: "2026 Brooklyn Nets", strength: 49, era: "rebuild" },
  { name: "2026 Portland Trail Blazers", strength: 51, era: "rebuild" },
];
